version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    working_directory: ~/project/DawgSocial
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd DawgSocial
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            cd DawgSocial
            python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
