version: 2.1

jobs:
  run-tests:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "pip install -r DawgSocial/requirements.txt"
      - run:
          name: "Change to DawgSocial directory"
          command: "cd DawgSocial"
      - run:
          name: "Run tests"
          command: "cd DawgSocial && python manage.py test"

workflows:
  version: 2
  test:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - main
