version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Apply Migrations
          command: |
            python manage.py migrate
  test:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
