version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "pip install -r requirements.txt"
      - run:
          name: "Run tests"
          command: "python manage.py test"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - run-tests:
          requires:
            - say-hello
